---
- name: Install Horizon in Ubuntu
  hosts: compute
  become: true

  tasks:

    - name: Install OpenStack Horizon
      apt:
        name: openstack-dashboard
        state: present


    - name: Start and enable Apache service
      service:
        name: apache2
        state: restarted
      become: true
