---
- name: Install Cinder
  hosts: etc
  become: true
  tasks:
    - name: Install Cinder Packages
      when:
        - ansible_distribution == 'Ubuntu'
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - cinder-api
        - cinder-scheduler
